title:              Ashvin Gupta
email:              ashvingupta00@gmail.com
description:        Ashvin Gupta
# author:             Start Bootstrap
baseurl:            ""
url:                ""

# Social Profiles
# twitter_username:   SBootstrap
github_username:    Ashvin-Gupta
# facebook_username:  StartBootstrap
# instagram_username:  
linkedin_username:    https://www.linkedin.com/in/ashvin-gupta-6a89991a1/

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
